langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/
      api-key: sk-f4829b30054b4468acf649d0a8e8af03
      model-name: qwen-plus
      temperature: 0.1
      # 配合温度使用，进一步限制随机性
      top-p: 0.8
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/
      api-key: sk-f4829b30054b4468acf649d0a8e8af03
      model-name: qwen-plus
      temperature: 0.1
      top-p: 0.8
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/
      api-key: sk-f4829b30054b4468acf649d0a8e8af03
      model-name: text-embedding-v4
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
  community:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379

# 第三方金融数据接口配置
financial:
  alpha-vantage:
    api-key: OZZPYYWT8IU8UQ4M  <-- 把你的Key填在这里
    base-url: https://www.alphavantage.co/query
  tushare:
    api-key: 3c2eb4602e20715251ecfe45d1eb0c98872394542c79f334e23623d8
    base-url: https://api.tushare.pro


